### PR TITLE
2.0.0-beta.2 released

### PR DESCRIPTION
**Pull request by lorenzoPrimi**

### CODE REVIEW

**Comment by hellais** [comment]
You should rebase this on top of master to get the travis fix

**Comment by lorenzoPrimi** [comment]
What does rebase means? merge it in master?

**Comment by hellais** [comment]
> What does rebase means? merge it in master?

Either merge or rebase master into this branch. See: https://www.atlassian.com/git/tutorials/merging-vs-rebasing

**Comment by lorenzoPrimi** [comment]
done

**Pull request merged**
